# Generated by Django 4.1.3 on 2022-11-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='className',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='professorName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='schoolName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='studentName',
            field=models.CharField(max_length=200),
        ),
    ]
