# Generated by Django 4.1.3 on 2022-11-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_school_classname_alter_school_professorname_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('className', 'studentName'), ('schoolName', 'className')},
        ),
    ]
