# Generated by Django 4.1.3 on 2022-11-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_school_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('schoolName', 'className', 'studentName')},
        ),
    ]
