# Generated by Django 4.1.3 on 2022-11-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_school_studentgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='className',
            field=models.CharField(default='No Data', max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='professorName',
            field=models.CharField(default='No Data', max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='schoolName',
            field=models.CharField(default='No Data', max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='studentName',
            field=models.CharField(default='No Data', max_length=200),
        ),
    ]
