# Generated by Django 4.1.3 on 2022-11-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_school_classname_alter_school_professorname_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('schoolName', 'className', 'studentName'), ('schoolName', 'className')},
        ),
    ]
